config/routes.rb
Simplapps::Application.routes.draw do

  devise_for :users

  match 'projects/portfolio' => 'projects#portfolio'
  match 'about' 			=> 'pages#about'
	match 'contact'			=> 'pages#contact'
	match 'services'			=> 'pages#services'

  resources :pages
  resources :projects

   root :to => "pages#home"

end

app/views/pages/_form.html.erb
<%= form_for @page do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :page_type %><br />
    <%= f.text_field :page_type %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.cktext_area :content, :toolbar=>"Full" %>
  </p>
  <p>
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/pages/display.html.erb
<% title @page.name %>

<p>
  <%= raw(@page.content) %>
</p>

<% content_for :metakeywords do %>
  <meta keywords="<%= @page.keywords %>">
<% end -%>

app/views/pages/edit.html.erb
<% title "Edit Page" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @page %> |
  <%= link_to "View All", pages_path %>
</p>

app/views/pages/home.html.erb
  <% content_for :body_tag do %>
    id="home"
  <% end %>

  <% title @page.name %>

  <p>
    <%= raw(@page.content) %>
  </p>
</article>
<article>
  <h3><%= @project.name %></h3>

  <p>
    <%= raw(@project.description) %>
  </p>
</article>
<article>
  <%= raw(@blog) %>

app/views/pages/index.html.erb
<% title "Pages" %>

<table>
  <tr>
    <th><p>Name</p></th>
    <th><p>Type</p></th>
  </tr>
  <% for page in @pages %>
    <tr>
      <td><p><%= page.name %></p></td>
      <td><p><%= page.page_type %></p></td>
      <td><p><%= link_to "Show", page %></p></td>
      <td><p><%= link_to "Edit", edit_page_path(page) %></p></td>
      <td><p><%= link_to "Delete", page_path(page), :method => :delete %></p></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Page", new_page_path %></p>

app/views/pages/new.html.erb
<% title "New Page" %>

<%= render 'form' %>

<p><%= link_to "Back to List", pages_path %></p>

app/views/pages/show.html.erb
<% title "Page" %>

<p>
  <strong>Name:</strong>
  <%= @page.name %>
</p>
<p>
  <strong>Type:</strong>
  <%= @page.page_type %>
</p>
<p>
  <strong>Keywords:</strong>
  <%= @page.keywords %>
</p>
<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <%= link_to "Edit", edit_page_path(@page) %> |
  <%= link_to "View All", pages_path %>
</p>