config/routes.rb
Simplapps::Application.routes.draw do

  devise_for :users

  match 'projects/portfolio' => 'projects#portfolio'
  match 'about' 			=> 'pages#about'
	match 'contact'			=> 'pages#contact'
	match 'services'			=> 'pages#services'

  resources :pages
  resources :projects

   root :to => "pages#home"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_attached_file :screenshot
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!, :except => [:portfolio]

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to @project, :notice => "Successfully created project."
    else
      render :action => 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to @project, :notice  => "Successfully updated project."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, :notice => "Successfully deleted project."
  end

  def portfolio
    @projects = Project.all
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<% form_for @project, :html => { :multipart => true } do |f| -%>
  <p><%= f.label :name %><br /><%= f.text_field :name %></ br>
    <p><%= f.label :project_type %><br /><%= f.text_field :project_type %></p>
    <p><%= f.label :client %><br /><%= f.text_field :client %></p>
    <p><%= f.label :description %><br /><%= f.cktext_area :description, :toolbar=>"Full" %></p>

    <p><%= f.label :screenshot, "Screenshot" %><br /><%= f.file_field :screenshot %></p>

    <p><%= f.submit %></p>
<% end -%>

app/views/projects/edit.html.erb
<% title "Edit Project" %>

<%= render :partial => "form" %>

app/views/projects/index.html.erb
<% title "Projects" %>

<table>
  <tr>
    <th><p>Project</p></th>
    <th><p>Type</p></th>
    <th><p>Client</p></th>
    <th>&nbsp</th>
    <th>&nbsp</th>
    <th>&nbsp</th>
  </tr>
  <% @projects.each do |project| -%>
    <tr>
      <td><p><%= project.name %></p></td>
      <td><p><%= project.project_type %></p></td>
      <td><p><%= project.client %></p></td>
      <td><p><%= link_to 'Show', project, :id => 'show' %></p></td>
      <td><p><%= link_to 'Edit', edit_project_path(project) %></p></td>
      <td><p><%= link_to 'Delete', project, :method => :delete  %></p></td>
     </tr>
  <% end -%>
</table>

<%= link_to 'New project', new_project_path %>

app/views/projects/new.html.erb
<% title "New Project" %>

<%= render :partial => "form" %>

<p><%= link_to "Back to List", projects_path %></p>

app/views/projects/portfolio.html.erb
<% title 'projects' %>

<ul id="myGallery">
  <% for project in @projects -%>
    <li><%= image_tag project.screenshot.url %>
      <div class="gv-panel-overlay">
        <h3><%= project.name %></h3>
        <p><%= project.description %></p>
       </div>
    </li>
  <% end -%>

</ul>

app/views/projects/show.html.erb
<% title @project.name %>

<%= @project.project_type %><br />
<%= @project.client %><br />
<%= raw(@project.description) %><br />
<%= @project.image %><br />


<%= link_to 'View All', projects_path %>