config/routes.rb
Simplapps::Application.routes.draw do

  devise_for :users

  match 'projects/portfolio' => 'projects#portfolio'
  match 'about' 			=> 'pages#about'
	match 'contact'			=> 'pages#contact'
	match 'services'			=> 'pages#services'

  resources :pages
  resources :projects

   root :to => "pages#home"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_footer.html.erb
<footer>
				<div class="wrap">
					<section class="first-col">
						<h4>Contact</h4>
						<p>If you would like to discuss a project, get a quote or ask a question then please either send an email or fill out the <a href="/contact">contact form</a> and we will get back to you.</p>
						<ul>
							<li>Email: info@simplapps.co.uk</li>
							<li>Contact Form: Click <a href="/contact">here</a></li>
							<li class="last">Doncaster, S. Yorks, UK</li>
						</ul>
					</section>
					<section>
						<h4>Colophon</h4>
						<p>We developed this website using Ruby on Rails v3. This allows us to easily change the content of the site.  It also allows us to track the projects we have worked on anddisplay their details on the website. The site is HTML5 and CSS3 validated.</p>
					</section>
					<section>
						<h4>Other Places To Find Us</h4>
						<ul>
							<li><a href="http://twitter.com/simplapps">Twitter</a></li>
							<li><a href="http://twitter.com/simplapps">LinkedIn</a></li>
							<li><a href="http://about.me/simplapps">About.Me</a></li>
							<li><a href="http://www.facebook.com/pages/Simplapps/215018771845425">Facebook</a></li>
							<li class="last"><a href="http://www.delicious.com/nicko777">Delicious</a></li>
						</ul>
					</section>
					<section class="full">
						&copy; 2011 <a href="www.simplapps.co.uk">SimplApps.co.uk</a>
						<div id="user_nav">
						  <% if user_signed_in? -%>
						    Signed in as <%= current_user.email %>. Not you? <%= link_to 'Sign out', destroy_user_session_path %>
						  <% else -%>
						    <%= link_to 'Sign in', new_user_session_path %>
						  <% end -%>
						</div>
					</section>
				</div>
			</footer>

app/views/layouts/_header.html.erb
<header class="wrap">
  <section id="branding">
    <h1><%= link_to (image_tag ('simplappslogo.png')), root_path %></h1>
    <h2>Simple web applications to make your life easier</h2>
  </section>
  <nav>
    <ul>
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Portfolio', 'projects/portfolio' %></li>
      <li><%= link_to 'Services', services_path %></li>
      <li><%= link_to 'Blog', 'http://simplapps.wordpress.com' %></li>
      <li><%= link_to 'Contact', contact_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_htmlhead.html.erb
<meta content="http://www.simplapps.co.uk/" name="author">
<meta charset="UTF-8">
<meta content="Hi, we are a web development company who make simple web apps that are easy to use and make life simple for our clients" name="description">
<%= yield(:metakeywords) %>
<%= stylesheet_link_tag "reset" %>
<%= stylesheet_link_tag 'main' %>
<%= stylesheet_link_tag 'jquery.galleryview-3.0.css' %>
<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js" %>
<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js" %>
<%= javascript_include_tag "jquery-rails.js" %>
<%= javascript_include_tag "application.js" %>
<%= javascript_include_tag "jquery.easing.1.3.js" %>
<%= javascript_include_tag "jquery.galleryview-3.0.min.js" %>
<%= javascript_include_tag "jquery.timers-1.2.js" %>
<%= javascript_include_tag :ckeditor %>
<link rel="shortcut icon" href="/favicon.ico" />
<%= csrf_meta_tag %>

<!--
  GOOGLE ANALYTICS
-->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-22952873-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= render :partial => "layouts/htmlhead" %>
    <%= yield(:head) %>
  </head>
  <body <%= yield :body_tag %> >
    <div id="container">
      <%= render :partial => "layouts/header" %>
      <section id="content">
				<div class="wrap">
          <% flash.each do |name, msg| %>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          <% end %>
          <article>
            <%= content_tag :h3, yield(:title) if show_title? %>
            <%= yield %>
          </article>
				</div>
			</section>
			<%= render :partial => "layouts/footer" %>
    </div>
  </body>
</html>